### PR TITLE
add Speaking JavaScript (ES5 version)

### PR DESCRIPTION
**Pull request by wellingguzman**
I would like to recommend Speaking JavaScript by Dr. Axel Rauschmayer, It's a good book and helped me a lot.

### CODE REVIEW

**Comment by thefln** [comment]
@WellingGuzman Thanks for the suggestion! It seems the book hasn't been updated since 2014. Do you believe it still holds value for newcomers today, considering all the new versions of EcmaScript?

**Comment by wellingguzman** [comment]
It's an old book, It doesn't cover anything beyond ES5, but it covers all the fundamentals of JS until ES5, which I believe are good topics to any one who want to really want to have a glance to the good and bad parts of JS.

I wanted to recommend it even though it's an old book, it has good reference for JavaScript, and that's why I explicit mark it as "ES5 version".

In bottom line, starting with this book the path for a newcomer might be longer and confusing (No class, no arrow function, promises, etc.) but it gives you a good foundation.

**Comment by thefln** [comment]
> In bottom line, starting with this book the path for a newcomer might be longer and confusing (No class, no arrow function, promises, etc.) but it gives you a good foundation.

Gotcha. Let's leave it out then, in the spirit of keeping things as fresh as possible.

**Comment by wellingguzman** [comment]
Absolutely! Makes sense.

**Pull request closed without merging**
